version: "2.1"
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/www:/usr/share/nginx/html
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        networks:
            - knight-network
    php:
        image: php:7.3-fpm
        volumes:
            - ./nginx/www:/www
        networks:
            - knight-network
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - knight-network
networks:
    knight-network:
